#!/bin/bash
#
# The identity used to fetch the profile is determined by the saved access token.
# No need to specify an identity; just authenticate with the desired user:
#
#    $ get-token john && get-profile jack
#    Forbidden
#

case "$1" in
    admin|john|jack|foo)
        ;;
    *)
        echo >&2 "$1: unknown user"
        exit 1
esac

http -v --style native DELETE "http://localhost:8082/profile/$1" "Authorization:Bearer $(<access_token.txt)"
