#!/bin/bash
#
# The identity used to fetch the profile is determined by the saved access token.
# No need to specify an identity; just authenticate with the desired user:
#
#    $ get-token john && get-metric jack
#    Forbidden
#

case "$1" in
    admin)
        u=admin
        ;;
    john)
        u=john
        ;;
    jack)
        u=jack
        ;;
    *)
        echo >&2 "$1: unknown user"
        exit 1
esac

base_url="http://localhost:8082"

#curl -s -w "%{http_code}" -H "Authorization:Bearer $(<access_token.txt)" "$base_url/metric/${u}" | jq
http -v --style=native "$base_url/metric/${1}" "Authorization:Bearer $(<access_token.txt)"
