#!/bin/bash

read -d '' -r json <<END_OF_JSON
[
  {
    "advice": "advice1",
    "username": "foo"
  }, {
    "advice": "advice2",
    "username": "bar"
  }, {
    "advice": "advice3",
    "username": "baz"
  }
]
END_OF_JSON

echo "$json" | http -v --style native POST localhost:8081/advice "Authorization:Bearer $(<access_token.txt)"
